### ISSUE TITLE
What happened with partial.js?

### ISSUE THREAD

**Issue by eMarek** [totaljs/framework#112]
So total.js is now partial.js as stable version?

**Comment by xstable** [comment]
OK, but why does the Page of partialjs is still online ???  Or is this another new Project? http://www.partialjs.com/

If this the "old" partialjs, maybe better remove the page and place a Link to total.js to clearify this for the users?!!

**Comment by petersirka** [comment]
@xstable I don't have any access to `partialjs.com` domain. The domain was stolen and I can't do anything with it. So yes, Total.js framework is another project by the same author.

**Comment by ememumoh** [comment]
Peter,
I did a quick check and found the below. can you contact the owner of this domain and concludes things with him. Honestly it is misleading: 

Domain Name: partialjs.com
Registry Domain ID: 1775086274_DOMAIN_COM-VRSN
Registrar WHOIS Server: whois.srsplus.com
Registrar URL: http://srsplus.com
Updated Date: 2016-01-09T18:16:24Z
Creation Date: 2013-01-21T14:54:59Z
Registrar Registration Expiration Date: 2017-01-21T14:54:59Z
Registrar: TLDS LLC. d/b/a SRSPlus
Registrar IANA ID: 320
Registrar Abuse Contact Email: abuse@web.com
Registrar Abuse Contact Phone: +1.8773812449
Reseller: 
Domain Status: clientTransferProhibited http://icann.org/epp#clientTransferProhibited
Registry Registrant ID:
Registrant Name: Anton Gajdosik
Registrant Organization: Web Site Design s.r.o.
Registrant Street: Sibirska 23 
Registrant City: Bratislava
Registrant State/Province: 
Registrant Postal Code: 83102
Registrant Country: SK
Registrant Phone: +421.254650421
Registrant Phone Ext.:
Registrant Fax: +421.254650423
Registrant Fax Ext.:
Registrant Email: gajdosik@wsd-europe.com
Registry Admin ID:
Admin Name: Anton Gajdosik
Admin Organization: Web Site Design s.r.o.
Admin Street: Sibirska 23 
Admin City: Bratislava
Admin State/Province: 
Admin Postal Code: 83102
Admin Country: SK
Admin Phone: +421.254650421
Admin Phone Ext.:
Admin Fax: +421.254650423
Admin Fax Ext.:
Admin Email: gajdosik@wsd-europe.com
Registry Tech ID:
Tech Name: Anton Gajdosik
Tech Organization: Web Site Design s.r.o.
Tech Street: Sibirska 23 
Tech City: Bratislava
Tech State/Province: 
Tech Postal Code: 83102
Tech Country: SK
Tech Phone: +421.254650421
Tech Phone Ext.:
Tech Fax: +421.254650423
Tech Fax Ext.:
Tech Email: gajdosik@wsd-europe.com
Name Server: ns3.wsdnet.sk
Name Server: ns4.wsdnet.sk
DNSSEC: Unsigned
URL of the ICANN WHOIS Data Problem Reporting System: http://wdprs.internic.net/ 
>>> Last update of WHOIS database: 2016-01-09T18:16:24Z <<<

For more information on Whois status codes, please visit https://www.icann.org/resources/pages/epp-status-codes-2014-06-16-en.

The data in SRSPlus's WHOIS database is provided to you by
SRSPlus for information purposes only, that is, to assist you in
obtaining information about or related to a domain name registration
record. SRSPlus makes this information available "as is," and
does not guarantee its accuracy. By submitting a WHOIS query, you
agree that you will use this data only for lawful purposes and that,
under no circumstances will you use this data to: (1) allow, enable,
or otherwise support the transmission of mass unsolicited, commercial
advertising or solicitations via direct mail, electronic mail, or by
telephone; or (2) enable high volume, automated, electronic processes
that apply to SRSPlus (or its systems). The compilation,
repackaging, dissemination or other use of this data is expressly
prohibited without the prior written consent of SRSPlus.
SRSPlus reserves the right to modify these terms at any time.
By submitting this query, you agree to abide by these terms.

Registrar: TLDS, LLC DBA SRSPLUS
Whois Server: whois.srsplus.com
Creation Date: 21-JAN-2013
Updated Date: 09-JAN-2016
Expiration Date: 21-JAN-2017

Nameserver: NS3.WSDNET.SK
Nameserver: NS4.WSDNET.SK

Registry Status: clientTransferProhibited

**Comment by petersirka** [comment]
Yes, this man stole my domain. I have his contact, but he is very bad man. Again: I can't do anything with this domain. __The worst thing in the world are people.__

PS: Thank you.

**Comment by buckle2000** [comment]
Stole... legally?
