### ISSUE TITLE
forever debug

### ISSUE THREAD

**Issue by maxxam11** [totaljs/framework#268]
Hi.
If run 
```
forever debug.js
```
then after a while (a few hours) app does not work (response 503 Service Unavailable), but it appears in the forever list
```
info:    Forever processes running
data:        uid  command             script     forever pid   id logfile                 uptime  
data:    [0] lVX0 /usr/local/bin/node debug.js   27474   27477    /root/.forever/lVX0.log 0:15:17:9.968 
...
```
while other apps in forever list there is no problem 

I use:
Ubuntu 14.04
node v0.12.0
vorever v0.14.1
total.js 1271

**Comment by petersirka** [comment]
Hi @maxxam11,
you do not to run debug.js with forever because debug.js watchs the application. Debug.js runs the application in other thread and if the application has a critical bug then the debug.js waits for a change in some application script (and then re-runs it again). Debug.js is only for development.

Forever use for `release.js`.

**Comment by maxxam11** [comment]
understood. Thank you very much.
