### ISSUE TITLE
How do we use totaljs and pm2 together?

### ISSUE THREAD

**Issue by evgeny-t** [totaljs/framework#379]
Hi @petersirka,

I'm trying to run totaljs app using pm2 manager.
When I run a demo app from `examples/angularjs-bootstrap` like this:

```
pm2 start index.js -i 1 --watch
```

it encounters an issue, I can see it in `pm2 logs`:

```
index-0 (out):     at SyncWriteStream.write (/home/etimoshenko/bin/node-v4.2.2-linux-x64/lib/node_modules/pm2/lib/ProcessContainer.js:143:36)
index-0 (out):     at Console.warn (console.js:44:16)
index-0 (out):     at process.send (/home/etimoshenko/bin/node-v4.2.2-linux-x64/lib/node_modules/pm2/lib/ProcessContainer.js:43:15)
index-0 (out):     at SyncWriteStream.write (/home/etimoshenko/bin/node-v4.2.2-linux-x64/lib/node_modules/pm2/lib/ProcessContainer.js:145:17)
index-0 (out):     at Console.warn (console.js:44:16)
index-0 (out):     at process.send (/home/etimoshenko/bin/node-v4.2.2-linux-x64/lib/node_modules/pm2/lib/ProcessContainer.js:43:15)
index-0 (out):     at SyncWriteStream.write (/home/etimoshenko/bin/node-v4.2.2-linux-x64/lib/node_modules/pm2/lib/ProcessContainer.js:145:17)
index-0 (out):     at Console.warn (console.js:44:16)
index-0 (out):     at process.send (/home/etimoshenko/bin/node-v4.2.2-linux-x64/lib/node_modules/pm2/lib/ProcessContainer.js:43:15)
index-0 (out): ======= 2016-03-22 10:22:07: RangeError: Maximum call stack size exceeded RangeError: Maximum call stack size exceeded
index-0 (out):     at isFinite (native)
index-0 (out):     at Buffer.write (buffer.js:534:14)
index-0 (out):     at fromString (buffer.js:115:26)
index-0 (out):     at new Buffer (buffer.js:54:12)
index-0 (out):     at decodeChunk (_stream_writable.js:247:13)
index-0 (out):     at writeOrBuffer (_stream_writable.js:256:11)
index-0 (out):     at WriteStream.Writable.write (_stream_writable.js:207:11)
index-0 (out):     at SyncWriteStream.write (/home/etimoshenko/bin/node-v4.2.2-linux-x64/lib/node_modules/pm2/lib/ProcessContainer.js:143:36)
index-0 (out):     at Console.warn (console.js:44:16)
index-0 (out):     at process.send (/home/etimoshenko/bin/node-v4.2.2-linux-x64/lib/node_modules/pm2/lib/ProcessContainer.js:43:15)
```

and application restarts every time it receives a http request (pid gets changed).

Is there any way to run a totaljs app using pm2?

Thanks

**Comment by petersirka** [comment]
Hi @evgeny-t,
which version of total.js do you use?

**Comment by evgeny-t** [comment]
1.9.7

**Comment by petersirka** [comment]
I have tried it and everything works:
![image](https://cloud.githubusercontent.com/assets/2414252/13945936/8962ee96-f011-11e5-90d0-ed56d779714c.png)

Which file do you run? I think that with `debug.js` file will not work because `debug.js` contains child processes. Create your own startup file:

```javascript
require('total.js').http('debug');
```

Thanks and give me a feedback.

**Comment by petersirka** [comment]
Mmmt, I wrote garbage before :-D

**Comment by petersirka** [comment]
I think that with PM2 cluster will not work.
Try to write your own implementation of cluster and run it as classic app in PM2.

https://github.com/totaljs/examples/blob/master/cluster/index.js

---

I'll look into the PM2 problem with the cluster today and I'll give you a feedback.

**Comment by petersirka** [comment]
Hi @evgeny-t,
it works correctly:

![image](https://cloud.githubusercontent.com/assets/2414252/13964287/53c6f05e-f069-11e5-90ba-fe93c2303e7f.png)

![image](https://cloud.githubusercontent.com/assets/2414252/13964297/5b3e9aa8-f069-11e5-8123-761425b3d702.png)

![image](https://cloud.githubusercontent.com/assets/2414252/13964309/62545968-f069-11e5-8fea-e56388317249.png)

Try to install latest beta version.

**Comment by petersirka** [comment]
I have tested it on node.js `v4.4.0` and everything works correctly too.
Thanks.

**Comment by evgeny-t** [comment]
Right, everything works fine. Looks like I misinterpreted logs.
Thank you for your time!

**Comment by fgnm** [comment]
Since with `+v2.6.0` clusters are built in Total and with `+v3.4.0` we have also auto-elasticity is it still possible to use pm2? What are the correct commands to run it?

I would like to achieve the zero-downtime update, but I'm worried about `websocket` and `cache`, it could be great to keep both when an update needs to be released.

I've also have a look to `SuperAdmin`, but I can't find anything that explicitly refer to zero-downtime.

**Comment by petersirka** [comment]
Currently not possible with PM2. But here is one solution:

- just create a file called `restart` (without body) and the framework will restart all threads and I think with zero-downtime

**Comment by fgnm** [comment]
Yes it works! Very nice, unfortunately it does not preserve socket connections and `CACHE` data.
I've saw `reload` command in PM2 works by restart one single process at time. How works Total `restart`? Do you think that is possible to keep socket and cache alive during reload?

Mine it's just an idea because I don't know very well how threads works in Total right now, but is this reload possible?
- Create a new process
- Migrate `CACHE` and Websockets from old process to the new one
- Remove old process

**Comment by petersirka** [comment]
> unfortunately it does not preserve socket connections and CACHE data.

Not possible to keep socket and cache data. Each process contains own data. For cluster you need to use e.g. REDIS (or another process) for storing e.g. session data.

CACHE can store persistent data (all data in cache are written on HDD). BTW: WebSocket can't be clusterized.

**Comment by fgnm** [comment]
Many Thanks! So I'll try to make something with REDIS in order to keep WebSockets alive
