### ISSUE TITLE
why don't support TypeScript?

### ISSUE THREAD

**Issue by kinglo** [totaljs/framework#416]

**Comment by petersirka** [comment]
Hi @kinglo,
sorry for my opinion, but __TypeScript__ is really useless. I don't see any benefits of it (same as CoffeScript, etc.). I like simple solutions with common sense 👍 and total.js is about that.

So I don't see any support for TS now. Who wants to use TS then can use ASP.NET MVC.

**Comment by michaeljota** [comment]
Is this still your posture about it? TS makes really easy to code and its useful for maintain the application. Several projects are looking forward Typescript, or even just making Typescript developers easy. The best thing about TS is that is just Javascript with strong typing. If you don't find this useful, I know what do you call 'common sense'. 

I just think that you have never try TypeScript, even the Angular 2 example it's outdated an in an old fashion JS.

**Comment by petersirka** [comment]
Hi, yes, but read this:
<http://maxprog.net.pl/node-js/total-js-angular2-typescript/>

**Comment by michaeljota** [comment]
Your point? 

At this moment, I can't tell if this can benefit with TypeScript, but it certainly is not useless. Anyhow, develop in JavaScript can be improve just with TS definitions, and I think this a great point that you are missing.

**Comment by petersirka** [comment]
I don't belive TS (sorry, it's my opinion) - really I don't need it, but I agree that TS can be helpful for a lot of developers. It's like a sado sex, a few people practices it 👍

**Comment by michaeljota** [comment]
It's ok. Some people don't believe in evolution either.

**Comment by teddis** [comment]
Without Typescript, this entire project is useless. Very sad, it looks so promising.

**Comment by BlueMagnificent** [comment]
@teddis I believe your use of the term "useless" is purely subjective. TypeScript is not a standard so I see no reason why a JavaScript based project is useless without it.

**Comment by teddis** [comment]
@BlueMagnificent I apologize, I misspoke. The project is not useless. It's just that strong typing is incredibly valuable to catch and prevent all sorts of bugs and enforce good programming practice. The author's flippant rejection is disheartening. It would be nice if the project at least included official typings as a courtesy to Typescript developers. This is certainly fine as a pure JavaScript project.

**Comment by petersirka** [comment]
@teddis I agree with valuable of TS, but I (personally) don't need it. Everyone can use TypeScript/Dart/CoffeeScript/Etc. but I don't have any support for it. __Nothing more.__

**Comment by moravcik** [comment]
@petersirka, I guess you are missing point of TypeScript. CoffeeScript is bad example in this case, as it is has its own (weird) syntax and nobody really use it. 

On the other hand TypeScript is a superset of ES6/ES7 with added types, which makes all programming interfaces readable, auto-complete-able, self-documented, less error-prone, easy to refactor, better maintainable, better testable, etc, etc. Types are optional, so one can write pure JavaScript and it is still valid TypeScript code. It is compiled to JavaScript with nice incremental-compilation support. Lately I see many libraries and frameworks moving to TypeScript, or providing typings for TypeScript, or at least written in ES6, as it leverages much cleaner syntax and standardized module system for all JavaScript environments. 

In my opinion I don't like using global variables (like `$`, or `F`) and `var self = this` in pure functions, because in JavaScript you never really know what you are going to get as `this` and with global-everything you can easily destroy everything. These are ones of ES5 JavaScript problems, which has been greatly reduced by ES6 syntax and purified with TypeScript types. 

In our company we started to use TypeScript for all JavaScript code and I think I can say that everyone is satisfied with benefits of coding in TypeScript.

**Comment by kevinclarkadstech** [comment]
LOL what a terrible attitude to have.  You don't have to use TS in your own programming but if you make a 3rd party lib and want to get other people to use it, you should be open to creating TypeScript definitions for people who do "believe in it".  For example Express has TS definitions at @types/express even though the library is not written in TS.  TypeScript has gained huge momentum, and there is a reason for it.  I will look at other Node.js frameworks, as I am sure a lot of other people will.

**Comment by rjamesnw** [comment]
I agree, for all its features, I'm worried about scalability of code. Finding obscure bugs in JS is much harder without the added type checking overlay that TypeScript provides at compile time. One change and easily break many things. The refactoring and code-completion support is a big help to increase development speed, without needing to constantly check online docs (for example, just to be reminded of parameters expected, and in which order). My team at a large international company I work at uses TS fully and will never go back to writing enterprise apps using only JS. I agree with Kevin that it does not mean you have to re-write everything.  You just need to create a definition file (`.d.ts`) for the system to making writing code, especially components, etc., much easier., then you can place it in `@types` for npm.

That said, Flow is a nice addition.  It makes the need for TS less, but one still needs to write new components for custom solutions/edge cases, so perhaps focus on Flow and add definition files for writing custom nodes for that at least.

Tip: There is already a nice free editor for TS here call "Monaco": https://microsoft.github.io/monaco-editor/
Play with it and you'll fall in love with it right away, and feel elated with all the possibilities. ;)

**Comment by kevinclarkadstech** [comment]
> I agree, for all its features, I'm worried about scalability of code. Finding obscure bugs in JS is much harder without the added type checking overlay that TypeScript provides at compile time. One change and easily break many things. The refactoring and code-completion support is a big help to increase development speed, without needing to constantly check online docs (for example, just to be reminded of parameters expected, and in which order). My team at a large international company I work at uses TS fully and will never go back to writing enterprise apps using only JS. I agree with Kevin that it does not mean you have to re-write everything. You just need to create a definition file (`.d.ts`) for the system to making writing code, especially components, etc., much easier., then you can place it in `@types` for npm.
> 
> That said, Flow is a nice addition. It makes the need for TS less, but one still needs to write new components for custom solutions/edge cases, so perhaps focus on Flow and add definition files for writing custom nodes for that at least.
> 
> Tip: There is already a nice free editor for TS here call "Monaco": https://microsoft.github.io/monaco-editor/
> Play with it and you'll fall in love with it right away, and feel elated with all the possibilities. ;)
> I'm writing an experimental low-code IDE platform with it already for NodeJS, as there are no good TypeScript-focused client+server frameworks I've found yet. Perhaps this is now a race on who gets there first. :P

If you look at popularity, NestJS has grown hugely in the last 1-2 years since it has been out...I bet a lot of it is because it is built on TS and has great TS support.  

Since Nov 2017 it has 20K stars and is used by 12K repositories (Used by 12,738 repositories).  @rjamesnw  I would look into that instead of wasting your time with trying to convince this dude about TS because from his replies (and lack of) you can tell he just doesn't get it.

But you said you are writing one so I am curious to what comes of it!

**Comment by petersirka** [comment]
As I said, **currently** we don't have any plan to implement TS. That's all.

**Comment by lobosan** [comment]
Still no plans?

**Comment by petersirka** [comment]
Sorry, but no.

**Comment by kevinclarkadstech** [comment]
Haha this guy...

**Comment by QazCetelic** [comment]
Just curious why do you think TypeScript is useless? I saw that [JSDoc comments were used](https://github.com/totaljs/framework/blob/57c33d28c3e584c11fef0a306336830e158f2d2a/image.js#L210) and was wondering why  you would use that when you don't deem adding types useful? Is it because you feel that it adds too much complexity to development or is there another reason? I'd be interested to hear it because I also noticed that the maintainers of Node-RED aren't interested in using it.

**Comment by petersirka** [comment]
I'm not a fan of TypeScript, but I understand that many developers use it. It's an extra thing in my opinion. I understand the maintainers of Node-RED, because I personally think it's a problem to compile it dynamically. I don't use it, so I can't give a relevant answer. I chose JavaScript because it's a great and beautiful language that allows you to do incredible things. I don't want to be alarmed by types and stuff. I love freedom and Javascript gives it to me.
