### ISSUE TITLE
RESTBuilder has no proxy support

### ISSUE THREAD

**Issue by li0nsar3c00l** [totaljs/framework#470]
I really like the RESTBuilder, but unfortunately it lacks support for proxies. Could you please add a property like in the http module?

**Comment by totaljs** [comment]
HI,
I'll look into it today.

Thank you

**Comment by li0nsar3c00l** [comment]
Highly appreciated, thanks. I guess more people, who have to operate behind corporate proxies would appreciate that as well. An implementation similar to C# [WebProxy](https://msdn.microsoft.com/en-us/library/system.net.webproxy(v=vs.110).aspx) would be awesome.

**Comment by petersirka** [comment]
I have looked into it and it's a bit complicated. I have to think about it because I have to rewrite a main method for creating requests (it isn't complicated for `http` request, but `https` requests are harder). I don't know now whether proxies will be implemented in newest version or in next version.

I'll give you a feedback.

**Comment by li0nsar3c00l** [comment]
Feel free to share your information on what and  which method needs to be changed. So I can look into it myself and maybe even provide  a pull request

**Comment by petersirka** [comment]
I recommend to use `request` module now but here is the method which performs requests:
<https://github.com/totaljs/framework/blob/v2.4.0/utils.js#L410>

**Comment by petersirka** [comment]
I won't implement proxy in near time. It's complicated for the current state.
