### ISSUE TITLE
Promises are not working

### ISSUE THREAD

**Issue by jozoraz** [totaljs/framework#498]
I don't know if it's just me, but I am not able to run a single promise with the framework

Could you please provide an example if they are working?
thanks

**Comment by petersirka** [comment]
Hi. Framework doesn't have implemented promises. Can you write me where do you want to implement them?

**Comment by jozoraz** [comment]
to my default component - I'd like to load data from the database first, and after everything is loaded, render them on the page

**Comment by petersirka** [comment]
Promises are slow but I understand that in some situations can improve readability of the code. I recommend to use Total.js Schemas.

```javacript
function some_aciton_in_controller() {
   var self = this;
   NOSQL('products').find().where('year', 2017).callback(self.callback('viewname'));
   // @{model} will contain array from Database
   // when DB returns an error then controller's returns 500
}
```

__Documentation:__ https://docs.totaljs.com/latest/en.html#api~FrameworkController~controller.callback

__Schemas__:

- __db__ https://github.com/totaljs/eshop/blob/master/models/products.js#L21
- __controller__ https://github.com/totaljs/eshop/blob/master/controllers/api.js#L65

**Comment by jozoraz** [comment]
thanks, it's working
and If I'd like to load data from a different website and render them on the page, but the data is not there, because the second page is not loaded yet, how could I fix that?

**Comment by petersirka** [comment]
For downloading data from another website you can use [RESTBuilder](https://docs.totaljs.com/latest/en.html#api~RESTBuilder) or `U.request()` or `U.download()`.

Then I recommend to use Schemas again because it supports [chaining (example)](https://github.com/totaljs/helpdesk/blob/master/controllers/api.js#L102).

__Other solutions__ for multiple async operations in a row:
- `Array.async()` https://docs.totaljs.com/latest/en.html#api~Array.prototype~Array.prototype.async
- `Array.wait()` https://docs.totaljs.com/latest/en.html#api~Array.prototype~Array.prototype.wait
