### ISSUE TITLE
restful2 slash bug

### ISSUE THREAD

**Issue by dacrhu** [totaljs/framework#537]
Hi Peter,

restful2 get method have a litle bug:

```
// simple email, wrong result
[dacr@berci ~]$ curl "http://127.0.0.1:8000/admin/users/dacr@dacr.hu"
404: Not Found

//email with slash, expected result
[dacr@berci ~]$ curl "http://127.0.0.1:8000/admin/users/dacr@dacr.hu/"
{"success":true,"value":...}

//without special character, expected result
[dacr@berci ~]$ curl "http://127.0.0.1:8000/admin/users/dacr"
{"success":false,"value":"User not found"}

//without special character, with slash, expected result
[dacr@berci ~]$ curl "http://127.0.0.1:8000/admin/users/dacr/"
{"success":false,"value":"User not found"}
```

So if I use special character then I must close ID with a slash.

Thank you,
David

**Comment by petersirka** [comment]
Hi @dacrhu,
`at` can't be in URL address because it's a part of it. `@` is used for basic auth e.g. `http://name:password@totaljs.com`. The second problem is that email address contains `.` (dot) and Total.js recognizes `dot` in the URL address as a static file. 

- don't use email address as an identificator in URL
- you can replace charts to e.g. `@` --> `--` and `.` --> `__` and the conversion on the server-side will be simple:`dacr--dacr__hu`
- I recommend to use as identificators only fixed numbers and strings without diacritics

Thank you!

**Comment by dacrhu** [comment]
Ok, thank you, I modify my code.
