### ISSUE TITLE
Did we plan to split index.js into smaller modules

### ISSUE THREAD

**Issue by ckpiggy** [totaljs/framework#612]
Currently we got a huge index.js over 10k lines.
Did we plan to split it into smaller module ?
You can plan the road map and design the project structure, and I am very glad to follow your rules to send some PR for the project.

**Comment by petersirka** [comment]
Hi @ckpiggy,
no, it's not plan because each module loads/processes code into the memory. So it doesn't matter if the code is in smaller modules or in the one bigger file. One bigger file saves memory because each module creates a new instance of module. The code is not pretty, but it's optimized for the best performance. 

The code contains comments and the line sometimes contains max. 3 chars...

---

My plan is to keep current funcionallity and max improve it. The code contains older codet too (not much) but it must stay because of backward compatibility. I agree, code is bigger but functionality too.

Thank you!

---

__Roadmap__:

I prepare `v3` with great new/updated features. E.g. components can contain new async render method --> this is really cool feature (I rewrote a part of View Engine). And next: schemas contain `.setInsert()` and `.setUpdate()` delegates.

<https://github.com/totaljs/framework/blob/v3.0.0/changes.txt>
