### ISSUE TITLE
F.onAuthorize and session

### ISSUE THREAD

**Issue by gibson** [totaljs/framework#650]
Why F.onAuthorize run before session module initialize? I have in session data from passport.js and i want use this data for set auth status, but cant - in F.onAuthorize req doesnt have session property

**Comment by petersirka** [comment]
Hi @gibson,
because on the state from `F.onAuthorize` depends next processing of the request. I think that you use a global middleware, but update it in some definition file to:

```javascript
F.use('session', '*', ['web']);
```

And the middleware with session will be executeda after `F.onAuthorize`. Global middleware is executed before is the request processed.

That's explation 💯

**Comment by gibson** [comment]
i need execute `session` module before `F.onAuthorize`

**Comment by petersirka** [comment]
Aha ... Then you need to use a global middleware and you can do it like this:

```javascript
F.use('session');
```

BTW: this global middleware is for all requests, so update your middleware like that:

```javascript
F.middleware('session', function(req, res, next) {
    if (req.isStaticFile)
        return next();
    // ... your code
    // ... your code
    // ... your code
    // ... your code
});
```

Or you can call `session` in `F.onAuthorize` directly:

```javascript
F.onAuthorize = function(req, res, flags, next) {
    YOURSESSION(req, res, function(session) {
         // your logic for authorization
    });
};
```

**Comment by gibson** [comment]
thx, its working
