### ISSUE TITLE
NOSQL builder.search can not search with nested property name

### ISSUE THREAD

**Issue by aalfiann** [totaljs/framework#714]
Hello,

I have problem that I can not search with nested property name when using NOSQL embedded builder.

I have database like this:
**users.nosql**
```
{"id":"19070212570001dnd1","name":"Aziz","datecreated":"2019-07-02T05:57:58.476Z"}
{"id":"19070212570002dnd0","name":"Tika","datecreated":"2019-07-02T05:57:58.476Z"}
```
**profile.nosql**
```
{"id":"19070212570001dnd1","about":"webmaster","address":"Jakarta"}
{"id":"19070212570002dnd0","about":"admin","address":"Jakarta"}
```

The problems is I can not to search the nested property name **about**. 
For example I want to search user who have about as admin.

I have tried like this
Searching for **about**
```
var users = NOSQL('users');
var search= 'admin';

// Reads the profile
users.find().make(function(builder) {
  var profile = builder.join('id', NOSQL('profile')).on('id', 'id');
  profile.first();
  builder.or();
  builder.search('name', search);
  profile.search('about', search);
  builder.end();
			
  builder.callback(function (err,response,count){
    console.log(response);
  });
});
```

the response output is
`[]`

when I try to search by name **tika** >> **WORK** but the output data is **NOT COMPLETE** because data from join is not appear.
```
[{
	"name": "Tika",
	"datecreated": "2019-07-02T05:57:58.476Z"
}]
```

when I try to search '' >> **WORK** and the output data is complete.
```
[{
	"id": {
		"id": "19070212570001dnd1",
		"about": "webmaster",
		"address": "Jakarta"
	},
	"name": "Aziz",
	"datecreated": "2019-07-02T05:57:58.476Z"
}, {
	"id": {
		"id": "19070212570002dnd0",
		"about": "admin",
		"address": "Jakarta"
	},
	"name": "Tika",
	"datecreated": "2019-07-02T05:57:58.476Z"
}]
```

Whats the problem? Am I missing something?

My goal is I am able to search by **name** or **about**.

Please help me, because I didn't found any example about this case and the documentation is not explain detail about search with join.

**Comment by petersirka** [comment]
Hi.
your filter is wrong:

```javascript
builder.or();
builder.search('name', search);
// you can't mix "builder" with "profile" because of the reason described below
profile.search('about', search);
builder.end();
```
NoSQL database is a very simple database and you can't do what you do. The reason is simple:

- filtering via `builder` is applied only for `users`
- filtering via `profile` is applied only for `profile`
- you can't mix them in `builder.or()`
- Total.js NoSQL database doesn't evaluate reading data as a relational database

First, database finds records in `users` database. Then, it reads all `id` (according to `.on()` method) in `users` (which are loaded in memory) and then tries to perform a second call to `profile` database. That's the reason why our filter doesn't work. In other words: joining of `profile` database depends on the results from `users` database.

I recommend to save `profile` to a user document, or you need to count with the fact, that filtering between two databases won't work as you're expecting.

Let me know if you have any further questions.

**Comment by aalfiann** [comment]
Ok, I get it now.

But, I hope there is a feature or method to solve this case in the future.

For this time, I will try to do transform the output first then manually filter them later.

Thank you

**Comment by petersirka** [comment]
I understand and I agree. But it's a bit complicated to make joins between databases. It's possible but there I need more time for research. The database is targeted for small projects and I recommend to think `documentable`, not relational.

Let me know if you have any questions.
