### ISSUE TITLE
How to onload in totaljs 4

### ISSUE THREAD

**Issue by aalfiann** [totaljs/framework#791]
Hello sir,
How to onload at first time?

I've put this at index.js but not working in TotalJS4,but in TotalJS3 works.
```
F.on('load', function() {
    // Now "load" event will work
});
```

Full source index.js
```
'use strict';

// ===================================================
// Total.js start script
// https://www.totaljs.com
// ===================================================

const options = {};

const type = process.argv.indexOf('--release', 1) !== -1 || process.argv.indexOf('release', 1) !== -1 ? 'release' : 'debug';

require('total4/' + type)(options);
const binance = require(F.path.definitions('binance'));

F.on('load', function () {
  // request only once at first time
  binance.getExchangeInfo().then(function (response) {
    console.log(response);
  }).catch(function (err) {
    console.log(err);
  });
});
```

Thank you..

**Comment by petersirka** [comment]
Hi @aalfiann, make a definition file e.g. `/definitions/ready.js`:

```js
ON('ready', function() {
    // do something
});
```

Don't use custom code in the `index.js` file because the `index.js` file is a starter script, and the script can execute another thread, so your event listener should not work. Everything store in the project structure like definitions, modules, controllers, schemas, etc..

**Comment by aalfiann** [comment]
I see, now I got this worked.

Thank you
